server:
  interface: 127.0.0.1
  port: 5335
  username: "unbound"
  directory: "/etc/unbound"
  chroot: ""
  root-hints: "/usr/share/dns/root.hints"
  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes
  prefer-ip6: no
  harden-glue: yes
  harden-dnssec-stripped: yes
  harden-below-nxdomain: yes
  harden-referral-path: no
  qname-minimisation: yes
  aggressive-nsec: yes
  prefetch: yes
  prefetch-key: yes
  serve-expired: yes
  serve-expired-ttl: 86400
  cache-min-ttl: 0
  cache-max-ttl: 86400
  rrset-cache-size: 128m
  msg-cache-size: 64m
  num-threads: 2
  so-reuseport: yes
  hide-identity: yes
  hide-version: yes
  statistics-interval: 0
  extended-statistics: yes

remote-control:
  control-enable: yes
  control-interface: /run/unbound.ctl
