apiVersion: 1

datasources:
  - name: Prometheus-vLLM
    uid: prometheus-vllm
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 3.14.0
