http:
  middlewares:
    chain-authelia-nowaf:
      chain:
        middlewares:
          - test-errors
          - realip
          - robotstxt
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authelia
            #          - coraza-waf
            #          - crowdsec
