http:
  middlewares:
    chain-no-auth-no-waf:
      chain:
        middlewares:
          - test-errors
          - realip
          - geoblock-badies
          - middlewares-rate-limit
          - middlewares-secure-headers
            #          - coraza-waf
            #          - crowdsec
