http:
  middlewares:
    coraza-waf:
      plugin:
        coraza:
          directives:
            #            - Include @coraza.conf-recommended
            - SecRuleEngine On
            - SecDebugLog /dev/stdout
            - SecDebugLogLevel 9
            - SecRule REQUEST_URI "@streq /admin" "id:101,phase:1,log,deny,status:403"
            - SecRule REQUEST_URI "@streq /.env " "id:102,phase:1,log,deny,status:403"
            - SecRule &REQUEST_HEADERS:x-middleware-subrequest "@gt 0" "id:1000001,phase:1,msg:'Request contains x-middleware-subrequest header',deny,status:403"                            
              #            - Include @owasp_crs/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
           # - Include @recommended-conf
           # - Include @crs-setup-conf
           # - Include @owasp_crs/*.conf
