http:
  middlewares:
    middlewares-rate-limit:
      rateLimit:
        average: 1000
        burst: 2000

    authelia-brute-force-limit:
      rateLimit:
        average: 5
        period: 5m
        burst: 10
        sourceCriterion:
          requestHeaderName: "Cf-Connecting-Ip"
