http:
    middlewares:
      waf:
            plugin:
                traefik-modsecurity-plugin:
                    MaxBodySize: "10485760"
                    ModsecurityUrl: http://waf:8080
                    TimeoutMillis: "2000"

