http:
  middlewares:
    fail2ban:
      plugin:
        fail2ban:
          sourceCriterion:
            requestHeaderName: "Cf-Connecting-Ip"
          allowlist:
            ip:
              - "10.0.0.0/8"
              - "172.16.0.0/12"
              - "192.168.0.0/16"
          rules:
            enabled: true
            bantime: "24h"
            findtime: "10m"
            maxretry: 10
            statuscode: "403"
