http:
  services:
    error-pages:
      loadBalancer:
        servers:
          - url: "http://error-pages:80"

  middlewares:
    test-errors:
      errors:
        status:
          - "400"
          - "401"
          - "403"
          - "404"
          - "405"
          - "408"
          - "429"
          - "500"
          - "502"
          - "503"
          - "504"
        service: error-pages
        query: "/{status}.html"
