http:
  middlewares:
    fail2ban:
      plugin:
        fail2ban:
          sourceCriterion:
            requestHeaderName: "Cf-Connecting-Ip"
          logLevel: "WARN"
          rules:
            enabled: true
            bantime: "24h"
            findtime: "10m"
            maxretry: 10
            statuscode: "403"
