http:
  #  serversTransports:
  #    insecureSkipVerify: true

  routers:
    u1-http:
      entryPoints:
        - "https"
      rule: Host(`u1.sketchyasfuckistan.net`)
      middlewares:
        - chain-authelia-nowaf
      service: "u1"
      tls:
        certresolver: letsencrypt
        domains:
          - main: "sketchyasfuckistan.net"
            sans:
              - "*.sketchyasfuckistan.net"

  services:
    u1:
      loadBalancer:
        servers:
          - url: "http://u1.hirschnet/"
